name: Cask Version Updater

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run updater
        run: ruby Scripts/CaskVersionUpdater.rb
      - name: Check diff
        id: diff
        run: |
          git add -N Casks/
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Casks/
          git commit -m "Version update by Actions"
          git push origin HEAD
        if: steps.diff.outcome == 'failure'
